name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask  
  - wheel
  - requests
  - click
  - tifffile
  - pillow
  - python-dateutil
  - utm
  - shapely
  - boto3
  - botocore
  - pyproj
  - sentinelhub